// Generated by CoffeeScript 1.4.0
var support;

module.exports = support = {
  fn2modules: function(fn) {
    var arg, chain, depth, module, modules, name, narg, nested, nestings, _i, _j, _len, _len1, _ref, _ref1;
    modules = [];
    _ref = fn.fing.args;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      module = arg.name;
      if (module.match(/^_arg/)) {
        console.log('\n\n%s\n\n', fn.toString());
        nestings = [];
        _ref1 = fn.toString().match(/_(arg|ref)\.(\w*)/g);
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          narg = _ref1[_j];
          chain = narg.split('.');
          nested = [];
          name = chain[1];
          depth = chain.length;
          if (fn.toString().match(new RegExp("" + name + " = _arg." + name))) {
            depth = 1;
          }
          nested.push(depth);
          nested.push(name);
          nestings.push(nested);
        }
        modules.push({
          _nested: nestings
        });
      } else {
        modules.push({
          module: arg.name
        });
      }
    }
    return modules;
  }
};
