// Generated by CoffeeScript 1.4.0
var injector, support;

support = require('./injector_support');

injector = {
  inject: function() {
    var fn, key, list;
    if (typeof arguments[0] === 'function') {
      fn = arguments[0];
      return fn.apply(null, support.loadServices(support.fn2modules(fn)));
    } else {
      list = arguments[0];
      for (key in arguments) {
        fn = arguments[key];
      }
      return fn.apply(null, support.loadServices(support.fn2modules(fn), list));
    }
  }
};

module.exports = injector;
