// Generated by CoffeeScript 1.4.0
var support;

module.exports = support = {
  fn2modules: function(fn) {
    var arg, module, modules, parts, _i, _len, _ref;
    modules = [];
    _ref = fn.fing.args;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      module = arg.name;
      if (module.match(/\$/)) {
        parts = module.split('$');
        modules.push({
          module: parts[0],
          chain: parts.slice(1, +(parts.length - 1) + 1 || 9e9)
        });
      } else {
        modules.push({
          module: module
        });
      }
    }
    return modules;
  }
};
