// Generated by CoffeeScript 1.4.0
var injector;

module.exports = injector = {
  inject: function() {
    var fn, key, list;
    if (typeof arguments[0] === 'function') {
      fn = arguments[0];
      return fn.apply(null, injector.loadServices(fn.fing.args));
    } else {
      list = arguments[0];
      for (key in arguments) {
        fn = arguments[key];
      }
      return fn.apply(null, injector.loadServices(fn.fing.args, list));
    }
  }
};
