// Generated by CoffeeScript 1.4.0
var Shell, colors, git, waterfall;

Shell = require('../shell/shell');

colors = require('colors');

waterfall = require('async').waterfall;

module.exports = git = {
  repo: require('./git_repo'),
  tree: require('./git_tree')
};
