// Generated by CoffeeScript 1.4.0
var kit;

module.exports = kit = {
  shell: require('./shell/shell'),
  git: require('./git/git'),
  npm: require('./npm/npm'),
  coffee: require('./coffee/coffee'),
  set: require('./set/set'),
  injector: require('./injector/injector')
};
