// Generated by CoffeeScript 1.4.0
var Git, GitRepo, NodeModule,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Git = require('../git/git_support');

GitRepo = require('../git/git_repo');

module.exports = NodeModule = (function(_super) {

  __extends(NodeModule, _super);

  function NodeModule() {
    return NodeModule.__super__.constructor.apply(this, arguments);
  }

  NodeModule.init = function(workDir, seq, manager) {
    return new NodeModule({
      root: seq === 0,
      path: workDir,
      origin: Git.showOrigin(workDir),
      branch: Git.showBranch(workDir),
      ref: Git.showRef(workDir),
      manager: manager
    });
  };

  return NodeModule;

})(GitRepo);
