// Generated by CoffeeScript 1.4.0
var GitRepo, Package,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

GitRepo = require('../git/git_repo');

module.exports = Package = (function(_super) {

  __extends(Package, _super);

  function Package() {
    return Package.__super__.constructor.apply(this, arguments);
  }

  return Package;

})(GitRepo);
